//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalendarSerivce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public Tasks()
        {
            this.Works = new HashSet<Works>();
        }

        public Tasks(string TaskName, string Description, System.DateTime CreationDate, int HoursForResolve) 
        {
            this.TaskName = TaskName;
            this.Description = Description;
            this.CreationDate = CreationDate;
            this.HoursForResolve = HoursForResolve;
        }
    
        public int Id { get; set; }
        public string TaskName { get; set; }
        public string Description { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int HoursForResolve { get; set; }
    
        public virtual ICollection<Works> Works { get; set; }
    }
}
