//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalendarSerivce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Works
    {
        public int Id { get; set; }
        public string WorkName { get; set; }
        public string Description { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int SpendHours { get; set; }
        public int TasksId { get; set; }
    
        public virtual Tasks Tasks { get; set; }
    }
}
